"use client";
import { useState } from "react";
import { ArrowUpRight, ArrowDown, Code2, Search, Check, Menu, X } from "lucide-react";
import { Dialog, DialogContent, DialogTitle, DialogDescription } from "@/components/ui/dialog";
import InquiryForm from "@/components/inquiry-form";
const assetBase=process.env.NEXT_PUBLIC_BASE_PATH || "";
const projects=[{name:"Pro Auto Tek",url:"https://proautotek.com/",logo:"/logos/proautotek.png",logoWidth:2171,logoHeight:724,type:"Automotive",color:"auto"},{name:"Siesta Free Ride",url:"https://siestafreeride.com/",logo:"/logos/siesta-free-ride.png",logoWidth:1350,logoHeight:1165,type:"Transportation",color:"siesta"},{name:"Gutters STL",url:"https://guttersstl.com/",logo:"/logos/gutters-stl.png",logoWidth:1748,logoHeight:900,type:"Seamless gutters",color:"home"}];
export default function Home(){const[booking,setBooking]=useState(false);const[menu,setMenu]=useState(false);return <>
<header className="wrap site-header"><a className="brand" href="#" aria-label="Penguin Digital Co home"><b className="monogram">P<i/></b><span>PENGUIN<small>DIGITAL CO.</small></span></a><nav className={menu?"nav open":"nav"} aria-label="Main navigation">{[["What we do","services"],["The work","work"],["Our approach","approach"],["Plans","plans"]].map(([name,id])=><a key={id} href={`#${id}`} onClick={()=>setMenu(false)}>{name}</a>)}</nav><button className="button small header-cta" onClick={()=>setBooking(true)}>Let’s talk <ArrowUpRight size={17}/></button><button className="menu-toggle" aria-expanded={menu} aria-label={menu?"Close menu":"Open menu"} onClick={()=>setMenu(!menu)}>{menu?<X/>:<Menu/>}</button></header>
<main><section className="hero wrap"><div><p className="eyebrow">WEB DESIGN + SEO MANAGEMENT</p><h1>LOOK SHARP.<br/>GET FOUND.<br/><em>GROW BOLD.</em></h1><p className="hero-description">A website that feels like you. A search strategy that brings people to it. Let’s build your next chapter online.</p><button className="button" onClick={()=>setBooking(true)}>Request a consultation <ArrowUpRight size={20}/></button><a className="quiet-link" href="#services">Meet your digital partner <ArrowDown size={16}/></a></div><div className="hero-art"><img src={`${assetBase}/penguin-hero-dark.png`} alt="Friendly black and white penguin on a glowing lime platform against a midnight-blue background"/><div className="art-tag">A LITTLE DIFFERENT.<strong>BY DESIGN.</strong></div><span className="art-caption">GOOD DESIGN. SOLID FOOTING.</span></div></section>
<div className="ticker"><span>DESIGN WITH PURPOSE</span><i>✳</i><span>BUILD FOR PEOPLE</span><i>✳</i><span>GET DISCOVERED</span><i>✳</i><span>KEEP GROWING</span></div>
<section className="section wrap" id="services"><div className="section-heading"><p className="eyebrow">01 / WHAT WE DO</p><h2>GOOD LOOKS.<br/>REAL <em>FUNCTION.</em></h2><p>Your website and your search presence should work together. We connect the dots.</p></div><div className="service-grid">{[{name:<>WEB<br/>DESIGN.</>,icon:<Code2 size={30}/>,description:"Make the right first impression—and make the next step easy. Custom websites built around your business and your customers.",items:["Custom, responsive design","Clear content and intuitive navigation","A strong technical foundation"],cta:"Let’s build your website",note:"Project-based · Scope agreed before we start"},{name:<>SEO<br/>MANAGEMENT.</>,icon:<Search size={30}/>,description:"Help the right people find you. Ongoing attention to your content, your search visibility, and the opportunities that matter.",items:["Keyword research and on-page SEO","Technical and local search improvements","Ongoing reporting and clear next steps"],cta:"Let’s grow your visibility",note:"Ongoing support · Tailored to your goals"}].map((s,i)=><article className={`service-card ${i?'blue':''}`} key={i}><div className="card-top">{s.icon}<span>0{i+1}</span></div><h3>{s.name}</h3><p>{s.description}</p><ul>{s.items.map(t=><li key={t}><Check size={17}/>{t}</li>)}</ul><button className="text-button" onClick={()=>setBooking(true)}>{s.cta}<ArrowUpRight/></button><div className="payment-note">{s.note}</div></article>)}</div></section>
<section className="work-section" id="work"><div className="wrap"><div className="work-heading"><div><p className="eyebrow">02 / SELECTED WORK</p><h2>REAL BUSINESSES.<br/>DISTINCT <em>PERSONALITIES.</em></h2></div><p>Different industries.<br/>A thoughtful approach to each.</p></div><div className="portfolio-grid">{projects.map((p,i)=><a className="project" href={p.url} target="_blank" rel="noreferrer" key={p.url} aria-label={`Visit ${p.name} website (opens in a new tab)`}><div className={`project-preview ${p.color}`}><span>SELECTED WORK / 0{i+1}</span><div className="project-logo"><img src={`${assetBase}${p.logo}`} alt={`${p.name} logo`} width={p.logoWidth} height={p.logoHeight} loading="lazy" decoding="async"/></div><div className="project-meta"><span>{p.type}</span><ArrowUpRight size={24}/></div></div><div className="project-label"><h3>{p.name}</h3><ArrowUpRight size={18}/></div><p className="project-url">{new URL(p.url).hostname}</p></a>)}</div></div></section>
<section className="section wrap approach" id="approach"><div><p className="eyebrow">03 / OUR APPROACH</p><h2>LESS JARGON.<br/>MORE <em>MOMENTUM.</em></h2><p>Clear conversations, thoughtful decisions, and a plan you can understand.</p></div><div className="steps">{[["Start with your business.","We talk about your customers, your goals, and what’s getting in the way."],["Build with a purpose.","We shape the design and content around what visitors need to know—and do."],["Keep moving forward.","Launch with a clear next step. Keep improving with ongoing SEO support."]].map(([title,body],i)=><article key={title}><span>0{i+1}</span><div><h3>{title}</h3><p>{body}</p></div></article>)}</div></section>
<section className="section wrap pricing-section" id="plans"><div className="pricing-heading"><p className="eyebrow">MONTHLY PLANS</p><h2>SUPPORT FOR YOUR<br/><em>NEXT CHAPTER.</em></h2></div><div className="pricing-grid">{[{name:"Website Care",price:149,url:"https://buy.stripe.com/00weV537PdQb5RZdt8aIM01"},{name:"Local Growth",price:299,url:"https://buy.stripe.com/00wcMXcIph2ndkr9cSaIM02"},{name:"Growth Plus",price:599,url:"https://buy.stripe.com/5kQ28j5fX7rNbcj2OuaIM03"}].map(plan=><article className="pricing-card" key={plan.name}><h3>{plan.name}</h3><p className="plan-price"><strong>${plan.price}</strong><span>/ month</span></p><a className="button" href={plan.url} aria-label={`Subscribe to ${plan.name} for $${plan.price} per month`}>Choose this plan <ArrowUpRight size={18}/></a></article>)}</div><p className="plans-note">Billed monthly in USD. Secure checkout with Stripe.</p></section>
<section className="contact-section"><div className="wrap contact-inner"><p className="eyebrow">YOUR NEXT CHAPTER STARTS HERE</p><h2>LET’S MAKE<br/><em>SOME WAVES.</em></h2><p>Tell us where you are. Let’s figure out where you could go.</p><button className="button" onClick={()=>setBooking(true)}>Request a consultation <ArrowUpRight size={20}/></button></div></section></main>
<footer className="wrap"><a className="footer-brand" href="#"><img className="footer-mascot" src={`${assetBase}/penguin-digital-mascot.png`} width={1137} height={1383} alt="" loading="lazy" decoding="async"/><span>PENGUIN DIGITAL CO.</span></a><span>Web design. Search visibility. Your next chapter.</span><small>© {new Date().getFullYear()} Penguin Digital Co.</small><p className="powered-by">Powered by <strong>Penguin Investments</strong></p></footer>
<Dialog open={booking} onOpenChange={setBooking}><DialogContent className="booking-dialog"><p className="eyebrow">LET’S TALK ABOUT YOUR BUSINESS</p><DialogTitle className="dialog-title">A good place to start.</DialogTitle><DialogDescription className="dialog-description">Tell us a little about your business and what you have in mind. We’ll follow up to plan the next step.</DialogDescription><InquiryForm /></DialogContent></Dialog></>}
